apiVersion: v1
kind: Namespace
metadata:
  name: forward-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: forward-auth
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "50Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: echo
  namespace: forward-auth
  labels:
    app: echo
spec:
  type: ClusterIP
  selector:
    app: echo
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca
    nginx.ingress.kubernetes.io/auth-url: http://jwt-forward-auth.forward-auth.svc.cluster.local/
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Sub, X-Auth-Client-Id, X-Auth-Role, X-Auth-Scope, Authorization
  labels:
    app: echo
  name: echo
  namespace: forward-auth
spec:
  rules:
    - host: echo-auth.local
      http:
        paths:
          - backend:
              serviceName: echo
              servicePort: 80
  tls:
    - hosts:
        - echo-auth.local
      secretName: tls-echo-ingress
