name: Publish to Docker Hub
on:
  push:
    tags:
      - "v*"
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine tag name
        id: get_tag
        run: echo ::set-env name=GIT_TAG::${GITHUB_REF/refs\/tags\/v/}
      - name: Log in with Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t jwt-forward-auth .
      - name: Push to latest
        if: github.ref == 'refs/heads/master'
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:latest && docker push elssdu/jwt-forward-auth:latest
      - name: Push to tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:$GIT_TAG && docker push elssdu/jwt-forward-auth:$GIT_TAG
