name: Publish to Docker Hub
on:
  push:
    tags:
      - "release-*"
    branches:
      - master
      - "release-*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in with Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t jwt-forward-auth .

      - name: Push to latest
        if: github.ref == 'refs/heads/master'
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:latest && docker push elssdu/jwt-forward-auth:latest

      - name: Determine release tag
        if: startsWith(github.ref, 'refs/tags/release-')
        run: echo ::set-env name=RELEASE_TAG::${GITHUB_REF/refs\/tags\/release-/}
      - name: Push to release tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:$RELEASE_TAG && docker push elssdu/jwt-forward-auth:$RELEASE_TAG

      - name: Determine release branch
        if: startsWith(github.ref, 'refs/heads/release-')
        run: echo ::set-env name=RELEASE_BRANCH::${GITHUB_REF/refs\/heads\/release-/}
      - name: Push to release branch
        if: startsWith(github.ref, 'refs/heads/release-')
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:$RELEASE_BRANCH && docker push elssdu/jwt-forward-auth:$RELEASE_BRANCH
