name: Publish to Docker Hub
on:
  push:
    tags:
      - "v*"
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in with Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t jwt-forward-auth .

      - name: Push to latest
        if: github.ref == 'refs/heads/master'
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:latest && docker push elssdu/jwt-forward-auth:latest

      - name: Determine version tag
        id: get_tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-env name=VERSION_TAG::${GITHUB_REF/refs\/tags\/v/}
      - name: Push to version tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:$VERSION_TAG && docker push elssdu/jwt-forward-auth:$VERSION_TAG

      - name: Determine version branch
        id: get_tag
        if: startsWith(github.ref, 'refs/heads/v')
        run: echo ::set-env name=VERSION_BRANCH::${GITHUB_REF/refs\/heads\/v/}
      - name: Push to version tag
        if: startsWith(github.ref, 'refs/heads/v')
        run: docker tag jwt-forward-auth elssdu/jwt-forward-auth:$VERSION_BRANCH && docker push elssdu/jwt-forward-auth:$VERSION_BRANCH
