name: Publish Docker image
env:
  DOCKER_IMAGE: ghcr.io/elseu/sdu-jwt-forward-auth
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - develop
      - next
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Push to latest
        if: github.ref == 'refs/heads/master'
        run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest && docker push $DOCKER_IMAGE:latest

      - name: Push to next
        if: github.ref == 'refs/heads/next'
        run: docker tag $DOCKER_IMAGE $DOCKER_IMAGE:next && docker push $DOCKER_IMAGE:next

      - name: Push to versions
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION_SUFFIX=$(echo ${GITHUB_REF/refs\/tags\/v/} | sed -E s/[^-]+//)
          MAJOR_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/} | sed -E s/^\([0-9]+\).*$/\\1/ | sed -E s/-.*$//)
          MINOR_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/} | sed -E s/^\([0-9]+\.[0-9]+\).*$/\\1/ | sed -E s/-.*$//)
          FULL_VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/} | sed -E s/^\([0-9]+\.[0-9]+\.[0-9]+\).*$/\\1/ | sed -E s/-.*$//)
          if [ ! -z "$MAJOR_VERSION" ]; then
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$MAJOR_VERSION$VERSION_SUFFIX && docker push $DOCKER_IMAGE:$MAJOR_VERSION$VERSION_SUFFIX
          fi
          if [ ! -z "$MINOR_VERSION" ]; then
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$MINOR_VERSION$VERSION_SUFFIX && docker push $DOCKER_IMAGE:$MINOR_VERSION$VERSION_SUFFIX
          fi
          if [ ! -z "$FULL_VERSION" ]; then
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$FULL_VERSION$VERSION_SUFFIX && docker push $DOCKER_IMAGE:$FULL_VERSION$VERSION_SUFFIX
          fi
